- name: Create skywire directory
  file: path={{ GOPATH }}/src/github.com/skycoin state=directory

- name: Go to skywire directory and clone the git repository
  git: repo={{ SKYWIRE_REPO }}
       dest={{ GOPATH }}/src/github.com/skycoin/skywire
       accept_hostkey=yes

- name: Go to cmd directory and install the binaries
  shell: go install ./...
  args:
    chdir: "{{ GOPATH }}/src/github.com/skycoin/skywire/cmd"

- name: Go to go binaries folder and start manager in the background
  shell: ./manager -web-dir {{ GOPATH }}/src/github.com/skycoin/skywire/static/skywire-manager >{{MANAGERLOG}} 2>&1 &
  args:
    chdir: "{{ GOPATH }}/bin"

- name: Start a skywire node
  shell: ./node -connect-manager -manager-address :5998 -manager-web :8000 -discovery-address messenger.skycoin.net:5999 -address :5000 -web-port :6001 >{{ NODELOG }} 2>&1 &
  args:
    chdir: "{{ GOPATH }}/bin"
  
