- name: Create skywire directory
  file: path={{ GOPATH }}/src/github.com/skycoin state=directory

- name: Go to skywire directory and clone the git repository
  command: chdir=/opt/tools/temp git clone {{ skywire_repo }}

- name: Go to cmd directory and install the binaries
  command: chdir={{ GOPATH }}/src/github.com/skycoin/skywire/cmd go install ./...

- name: Go to go binaries folder and start manager in the background
  command: chdir={{ GOPATH }}/bin ./manager -web-dir {{ GOPATH }}/src/github.com/skycoin/skywire/static/skywire-manager >/dev/null 2>&1 &

- name: Start a skywire node
  shell: ./node -connect-manager -manager-address :5998 -manager-web :8000 -discovery-address messenger.skycoin.net:5999 -address :5000 -web-port :6001 >/dev/null 2>&1 &